<a href="https://colab.research.google.com/github/Tanitta023/My-Project/blob/main/essential_ptyhon_for_data_analyst.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Essential Python for Data Analyst** ##
- control flow + function
- OOP : Object Oriented Programming
- tny except handle error
- context manager, csv, json
- API
- web scraping => static website เว็บไซต์ง่ายๆ ไม่ได้ใช้จาวาสคริปมาก
- intro to data science libraries

In [ ]:
## function def
def hello(name):
    print("hi" + name) #กด tap ด้วยไม่งั้น error

In [ ]:
## lamda function
hello = lambda name: print("hi!" + name)

In [ ]:
hello()

hi!


In [ ]:
hello("ai")

hi!ai


In [ ]:
# control flow
# if for while



In [ ]:
# if elif else
def grading(score):
    # docstring
    """
    this function return grade for a student in UK
    """
    if score >= 70:
        return "Distinction"
    elif score >= 60:
        return "Merit"
    elif score >= 50:
        return "Passed"
    else:
        return "Failed"

In [ ]:
grading(80)

'Distinction'

In [ ]:
grading(64)

'Merit'

In [ ]:
grading(50)

'Passed'

In [ ]:
# return value from a function
def add_two_num(x,y):
    return x + y

result = add_two_num(10,15)
print(result)

In [ ]:
# for loop
nums = [1,2,3,4,5] ## => [2,4,6,8,10]

new_nums = [] # empty list

for num in nums:
    new_nums.append(num*2)

print(new_nums)



[2, 4, 6, 8, 10]


In [ ]:
# list comprehension
nums = [1,2,3,4,5]

y = [num*2 for num in nums]

print(y)

[2, 4, 6, 8, 10]


In [ ]:
## program to check odd/even numbers

nums = [35,50,22,21,28]

for num in nums:
    if num % 2 == 0:
        print(f"{num} is even")
    else:
        print(f"{num} is odd")

35 is odd
50 is even
22 is even
21 is odd
28 is even


In [ ]:
# while loop
count = 0

while count < 5: # True
    print("hello")
    # this line is very important
    count += 1 #(count = count + 1)

hello
hello
hello
hello
hello


In [ ]:
x = 1
x += 1
x += 1
x += 1
x -= 3
x *= 5
x *= 2
x /= 4
print(x)

2.5


In [ ]:
# get input from a user #รับเป็น str
def animal_guessing():
    set_animal = "hippo"
    answer = []
    while True:
        guess = input("Guess the animal: ")
        answer.append(guess)
        if guess == set_animal:
            print("Hooray! correct answer.")
            print(f"Logs: {answer}")
            break
        elif guess == "quit":
            print("See you next time.")
            break
        else:
            print("Nope! please try again.")

In [ ]:
animal_guessing()ca

Guess the animal: dog
Nope! please try again.
Guess the animal: cat
Nope! please try again.
Guess the animal: hippo
Hooray! correct answer.
Logs: ['dog', 'cat', 'hippo']


In [ ]:
## HW01 - create game pao yinh chub

In [ ]:
## OOP => Object Oriented Programming เขียนโค้ดเพื่อสร้างวัตถุอะไรสักอย่างขึ้นมา

## Dog
class Dog: #classตัวแรกใหญ่ตัวอื่นเล็ก
    # initialize
    def __init__(self, name, age, breed):
        self.name = name
        self.age = age
        self.breed = breed

    # dog methods (function) ฟังก์ชั่นที่สร้างขึ้นมาสำหรับclassนั้นๆ
    def sit(self):
        print("I'm sitting now.")

    def sleep(self):
        print("I'm sleeping now.")

    def get_older(self, year):
        self.age += year

In [ ]:
## create a new instance
dog1 = Dog("Mee", 1, "Pug")

In [ ]:
dog1.name

'Mee'

In [ ]:
dog1.sit()

I'm sitting now.


In [ ]:
## Dog method
dog1.get_older(3)
print(dog1.age)

7


In [ ]:
text = "a duck walk into a bar"

In [ ]:
## string method
text.split(" ") #เมื่อไหร่ก็ตามที่เจอspace จะตัดคำให้

['a', 'duck', 'walk', 'into', 'a', 'bar']

In [ ]:
"HELLO WORLD".lower()

'hello world'

In [ ]:
dog1.age

1

In [ ]:
dog2 = Dog("Muu", 3, "gloden")

In [ ]:
class Apple:
    def __init__(self, size, price, color):
        self.size = size
        self.price = price
        self.color = color

apple1 = Apple("medium", 5, "red")
print(apple1.size, apple1.price, apple1.color)

medium 5 red


In [ ]:
## Python Class => OOP
## Class => attribute: name, age, breed
## Class => method: function => sit, sleep, get older

In [ ]:
class Person:
    def __init__(self, name):
        self.name = name

## Superclass
class Employee(Person):
    def __init__(self, name, company, position):
        super().__init__(name)
        self.name = name
        self.company = company
        self.position = position
    def greeting(self):
        print(f"Hi my name is {self.name} and i work for {self.company}.")


In [ ]:
ps1 = Person("Ai")
ps2 = Employee("Shi", "Google", "Data Analyst")


In [ ]:
ps1

In [ ]:
ps2.name

'Shi'

In [ ]:
ps2.position

'Data Analyst'

In [ ]:
ps2.greeting()

Hi my name is Shi and i work for Google.


In [ ]:
## Superclass extend feature from base class

In [ ]:
็# HW01 - pao ying chub game
# HW02 - class ATM at least 5 method เงินในบัญชี ชื่อบัญชี ธนาคาร function ฝากเงิน ขอเงิน otp บลาๆ

class ATM:
    pass

In [ ]:
## try except block ดักจับ error
try:
    print(1/2)
except ZeroDivisionError:
    print("cannot devide by zero")
except NameError:
    print("Variable not found in our environment")
else:
    print("OK")
finally: #ไม่ว่าจะเกิดอะไรขึ้นก็จะปริ้นคำนี้อยู่ดี
    print("END")

0.5
OK
END


In [ ]:
## try except SyntaxEror
try:
    eval('print(1+5 ')
except:
    print("Syntax error")

Syntax error


In [ ]:
!pwd

/content


In [ ]:
!ls

friends.csv.rtf  sample_data


In [ ]:
!echo hello world

hello world


In [ ]:
!cat friends.csv

id,name,age,company
1,ai,23,Google
2,shi,24,Amazon
3,nata,25,Microsoft
4,ann,29,Meta
5,wan,25,Anaconda

In [ ]:
import csv

In [ ]:
# open csv file using read mode
file = open("friends.csv", "r")

In [ ]:
# read content in this file
data = csv.reader(file)

In [ ]:
for row in data:
    print(row)

['\ufeffid', 'name', 'age', 'company']
['1', 'ai', '23', 'Google']
['2', 'shi', '24', 'Amazon']
['3', 'nata', '25', 'Microsoft']
['4', 'ann', '29', 'Meta']
['5', 'wan', '25', 'Anaconda']


In [ ]:
# close file
file.close()

In [ ]:
# pandas ต้องมีเนต
import pandas as pd

# import csv
df = pd.read_csv("friends.csv")

# export csv
df.to_csv("haha.csv")

In [ ]:
## context manager => with
## use to open data file

In [ ]:
# import csv
from csv import reader, writer
result = []

with open ("friends.csv", "r") as file:
    data = reader(file)
    for row in data:
        result.append(row)

result

[['\ufeffid', 'name', 'age', 'company'],
 ['1', 'ai', '23', 'Google'],
 ['2', 'shi', '24', 'Amazon'],
 ['3', 'nata', '25', 'Microsoft'],
 ['4', 'ann', '29', 'Meta'],
 ['5', 'wan', '25', 'Anaconda']]

In [ ]:
# write mode ไม่มีเนต
import csv

header = ["id", "course", "students"]
body_data = [
    [1, "data science", 30],
    [2, "marketing", 28],
    [3, "power BI", 35]
]

with open("courses.csv", "w") as file:
    writer = csv.writer(file)
    writer.writerow(header)
    writer.writerows(body_data)

In [ ]:
!ls

courses.csv  friends.csv  sample_data


In [ ]:
!cat courses.csv

id,course,students
1,data science,30
2,marketing,28
3,power BI,35


In [ ]:
## dict => json
import json # .load(), .dump()
book = {
    "name": "How to be good boi",
    "year": 2018,
    "aunthor": "me and me",
    "favorite": True
}

with open("book.json", "w") as file:
    json.dump(book, file)
    print("Create file successfully!")

Create file successfully!


In [ ]:
!cat book.json

{"name": "How to be good boi", "year": 2018, "aunthor": "me and me", "favorite": true}

In [ ]:
try:
    with open("friends.csv"),
    data = csv.reader(file)
    for row in data:
        print(row)
except FileNotFoundError:
    print("Please check file again")
else:
    print("open file successfully")

In [ ]:
# API => Application Programming Interface
# Communication two machines

# request-response
from requests import get

url = "https://swapi.dev/api/people/1"

resp = get(url)

# if success, OK 200 if 404 = not found
resp.status_code

## see information
resp.json()["name"]

'Luke Skywalker'

In [ ]:
import requests
import time

characters = []

for i in range(5): #สร้างตัวเลข 1-5
    url = f"https://swapi.dev/api/people/{i+1}"
    resp = requests.get(url)
    if resp.status_code == 200:
        json_data = resp.json()
        characters.append(
           (json_data["name"],
            json_data["height"])
        )
    # break a second
    time.sleep(1) # หยุด 1 วินาที

print(characters)




[('Luke Skywalker', '172'), ('C-3PO', '167'), ('R2-D2', '96'), ('Darth Vader', '202'), ('Leia Organa', '150')]


In [ ]:
range(5)

range(0, 5)

In [ ]:
#HW03 - find public API and use python to get data

In [ ]:
# Web Scraping
# install new library on google colab
# pip => package manager in Python

!pip install gazpacho

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for gazpacho: filename=gazpacho-1.1-py3-none-any.whl size=7461 sha256=e50b826f32aeb7181d4c2d74730ba8a460b3b4dc340f1c2193cb5a02b0613667
  Stored in directory: /root/.cache/pip/wheels/9b/bf/9f/8c8849499462415fa5cdf0d9edb1103c189bdbece90c51488e
Successfully built gazpacho


In [ ]:
!pip list | grep "^g" #ดูว่าติดตั้ง library เสร็จหรือป่าว ในนี้มร gazpochoไหม

gast                             0.4.0
gazpacho                         1.1
gcsfs                            2023.6.0
gdown                            4.6.6
geemap                           0.28.2
gensim                           4.3.2
geocoder                         1.38.1
geographiclib                    2.0
geopandas                        0.13.2
geopy                            2.3.0
gin-config                       0.5.0
glob2                            0.7
google                           2.0.3
google-api-core                  2.11.1
google-api-python-client         2.84.0
google-auth                      2.17.3
google-auth-httplib2             0.1.1
google-auth-oauthlib             1.0.0
google-cloud-bigquery            3.10.0
google-cloud-bigquery-connection 1.12.1
google-cloud-bigquery-storage    2.22.0
google-cloud-core                2.3.3
google-cloud-datastore           2.15.2
google-cloud-firestore           2.11.1
google-cloud-functions           1.13.3
google-cloud-lan

In [ ]:
## import function
from gazpacho import Soup
import requests

In [ ]:
## web scraping basics

url = "https://www.imdb.com/search/title/?groups=top_100&sort=user_rating,desc"

html = requests.get(url) ## Accept-Language: en


In [ ]:
imdb = Soup(html.text)

In [ ]:
imdb.find("h1")

<h1 class="header">IMDb &quot;Top 100&quot;
(Sorted by IMDb Rating Descending) </h1>

In [ ]:
titles = imdb.find("h3", {"class": "lister-item-header"})

titles[0].strip() #.strip = clean data ลบเหลือเฉพาะชื่อหนัง

'1. The Shawshank Redemption (1994)'

In [ ]:

clean_titles = []

for titile in titles:
    clean_titles.append(titile.strip())

clean_titles

In [ ]:
# ทำอีกแบบ สั้นลง list comprehension
clean_titles = [title.strip() for title in titles]

clean_titles

['1. The Shawshank Redemption (1994)',
 '2. The Godfather (1972)',
 '3. The Dark Knight (2008)',
 "4. Schindler's List (1993)",
 '5. The Lord of the Rings: The Return of the King (2003)',
 '6. 12 Angry Men (1957)',
 '7. The Godfather Part II (1974)',
 '8. Pulp Fiction (1994)',
 '9. Fight Club (1999)',
 '10. The Lord of the Rings: The Fellowship of the Ring (2001)',
 '11. Inception (2010)',
 '12. Forrest Gump (1994)',
 '13. The Lord of the Rings: The Two Towers (2002)',
 '14. The Good, the Bad and the Ugly (1966)',
 '15. Spider-Man: Across the Spider-Verse (2023)',
 '16. Interstellar (2014)',
 '17. Goodfellas (1990)',
 '18. The Matrix (1999)',
 "19. One Flew Over the Cuckoo's Nest (1975)",
 '20. Star Wars: Episode V - The Empire Strikes Back (1980)',
 '21. The Silence of the Lambs (1991)',
 '22. Se7en (1995)',
 '23. Saving Private Ryan (1998)',
 '24. The Green Mile (1999)',
 '25. Star Wars: Episode IV - A New Hope (1977)',
 '26. City of God (2002)',
 '27. Spirited Away (2001)',
 '28. Te

In [ ]:
## get rating from the website
## div: ratings-imdb-rating

ratings = imdb.find("div", {"class": "ratings-imdb-rating"})

clean_ratings = [float(rating.strip())for rating in ratings]

clean_ratings

[9.3,
 9.2,
 9.0,
 9.0,
 9.0,
 9.0,
 9.0,
 8.9,
 8.8,
 8.8,
 8.8,
 8.8,
 8.8,
 8.8,
 8.7,
 8.7,
 8.7,
 8.7,
 8.7,
 8.7,
 8.6,
 8.6,
 8.6,
 8.6,
 8.6,
 8.6,
 8.6,
 8.6,
 8.6,
 8.6,
 8.6,
 8.6,
 8.5,
 8.5,
 8.5,
 8.5,
 8.5,
 8.5,
 8.5,
 8.5,
 8.5,
 8.5,
 8.5,
 8.5,
 8.5,
 8.5,
 8.5,
 8.5,
 8.5,
 8.5]

In [ ]:
import pandas as pd

# create dataframe
movie_database = pd.DataFrame(data = {
    "title" : clean_titles,
    "rating" : clean_ratings
})

# print first five rows
movie_database.head()

title  rating
0                 1. The Shawshank Redemption (1994)     9.3
1                            2. The Godfather (1972)     9.2
2                          3. The Dark Knight (2008)     9.0
3                         4. Schindler's List (1993)     9.0
4  5. The Lord of the Rings: The Return of the Ki...     9.0

In [ ]:
#HW04 - อยากได้คอลัมน์ใหม่ใน dataframe เป็น year คือมี ชื่อหนัง เรตติ้ง ปี นะจ๊ะ
#create Launched Year colums in a dataframe
#movie_data["year"] = . . .

Intro to Data Science Libraries

- numpy
- pandas
- sklearn (maching learning)
- statsmodel (statistics)

In [ ]:
# numerical python
# very fast


In [ ]:
import numpy as np

nums = [1,2,3,4,5]


In [ ]:
nums = np.array(nums) #เปลี่ยน[] (list) เป็น numpyarray

nums + 5

array([ 6,  7,  8,  9, 10])

In [ ]:
# Statistics calculation
nums.sum()
np.median(nums)
np.sum(nums)

15

In [ ]:
np.arange(10) + 1 # range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.linspace (0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
## 2nd array
n2 = np.array([
    [1,2],
    [3,4]
])

In [ ]:
print(n2, type(n2))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [ ]:
## matrix * matrix
## .dot notation

array([[1, 2],
       [3, 4]])

In [ ]:
m1 = np.array([[1,2],[5,5]])
m2 = np.array([[4,2],[1,2]])

In [ ]:
np.dot(m1, m2)

array([[ 6,  6],
       [25, 20]])

In [ ]:
# import pandans
# manage dataframe
import pandas as pd


In [ ]:
# read data from csv file
url = "https://gist.githubusercontent.com/seankross/a412dfbd88b3db70b74b/raw/5f23f993cd87c283ce766e7ac6b329ee7cc2e1d1/mtcars.csv"

mtcars = pd.read_csv(url)

In [ ]:
mtcars.shape #กี่row กี่ colums

(32, 12)

In [ ]:
mtcars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   model   32 non-null     object 
 1   mpg     32 non-null     float64
 2   cyl     32 non-null     int64  
 3   disp    32 non-null     float64
 4   hp      32 non-null     int64  
 5   drat    32 non-null     float64
 6   wt      32 non-null     float64
 7   qsec    32 non-null     float64
 8   vs      32 non-null     int64  
 9   am      32 non-null     int64  
 10  gear    32 non-null     int64  
 11  carb    32 non-null     int64  
dtypes: float64(5), int64(6), object(1)
memory usage: 3.1+ KB


In [ ]:
mtcars.head()

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [ ]:
df = mtcars[ ["model", "mpg", "hp"] ].tail(3)
df

model   mpg   hp
29   Ferrari Dino  19.7  175
30  Maserati Bora  15.0  335
31     Volvo 142E  21.4  109

In [ ]:
df["mpg_double"] = df["mpg"] * 2

In [ ]:
df.head()

model   mpg   hp  mpg_double
29   Ferrari Dino  19.7  175        39.4
30  Maserati Bora  15.0  335        30.0
31     Volvo 142E  21.4  109        42.8

In [ ]:
df["mpg"].mean()

18.7

In [ ]:
df.mpg.mean()

18.7

In [ ]:
colnames = list(df.columns)
colnames[0] = "New Model"
df.columns = colnames

df.head()

New Model   mpg   hp  mpg_double
29   Ferrari Dino  19.7  175        39.4
30  Maserati Bora  15.0  335        30.0
31     Volvo 142E  21.4  109        42.8

In [ ]:
df["New Model"]

29     Ferrari Dino
30    Maserati Bora
31       Volvo 142E
Name: New Model, dtype: object

In [ ]:
# สรุป ไม่แนะนำให้ใช้ space ใช้ _ ดีกว่า

In [ ]:
# filter traditional
mtcars[(mtcars["mpg"] >30) & (mtcars["hp"]>100)]

model   mpg  cyl  disp   hp  drat     wt  qsec  vs  am  gear  carb
27  Lotus Europa  30.4    4  95.1  113  3.77  1.513  16.9   1   1     5     2

In [ ]:
# pandas.query()
# condition used to filter dataframe
mtcars.query(" mpg > 30 and hp > 100 ")

model   mpg  cyl  disp   hp  drat     wt  qsec  vs  am  gear  carb
27  Lotus Europa  30.4    4  95.1  113  3.77  1.513  16.9   1   1     5     2

In [ ]:
# aggregate + group by
# read data

store = pd.read_csv("store.csv")

In [ ]:
col_names = list(store.columns)

In [ ]:
clean_col_names = [col.lower().replace(" ", "_").replace("-", "_") for col in col_names]

In [ ]:
# เปลี่ยนเป็นตัวเล็กแล้ว space เป็น ๘

In [ ]:
#clean column names
store.columns = clean_col_names

In [ ]:
store.head()

row_id        order_id  order_date   ship_date       ship_mode customer_id  \
0       1  CA-2019-152156   11/8/2019  11/11/2019    Second Class    CG-12520   
1       2  CA-2019-152156   11/8/2019  11/11/2019    Second Class    CG-12520   
2       3  CA-2019-138688   6/12/2019   6/16/2019    Second Class    DV-13045   
3       4  US-2018-108966  10/11/2018  10/18/2018  Standard Class    SO-20335   
4       5  US-2018-108966  10/11/2018  10/18/2018  Standard Class    SO-20335   

     customer_name    segment country/region             city  ...  \
0      Claire Gute   Consumer  United States        Henderson  ...   
1      Claire Gute   Consumer  United States        Henderson  ...   
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...   
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...   
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...   

  postal_code  region       product_id         category sub_category  \
0     42420.0   South  FUR-BO-10001798        Furniture    Bookcases   
1     42420.0   South  FUR-CH-10000454        Furniture       Chairs   
2     90036.0    West  OFF-LA-10000240  Office Supplies       Labels   
3     33311.0   South  FUR-TA-10000577        Furniture       Tables   
4     33311.0   South  OFF-ST-10000760  Office Supplies      Storage   

                                        product_name     sales  quantity  \
0                  Bush Somerset Collection Bookcase  261.9600         2   
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3   
2  Self-Adhesive Address Labels for Typewriters b...   14.6200         2   
3      Bretford CR4500 Series Slim Rectangular Table  957.5775         5   
4                     Eldon Fold 'N Roll Cart System   22.3680         2   

   discount    profit  
0      0.00   41.9136  
1      0.00  219.5820  
2      0.00    6.8714  
3      0.45 -383.0310  
4      0.20    2.5164  

[5 rows x 21 columns]

In [ ]:
store["sales"].sum()

2297200.8603000003

In [ ]:
store.groupby("region")["sales"].sum()

region
Central    501239.8908
East       678781.2400
South      391721.9050
West       725457.8245
Name: sales, dtype: float64

In [ ]:
store.groupby("segment")["sales"].sum()

segment
Consumer       1.161401e+06
Corporate      7.061464e+05
Home Office    4.296531e+05
Name: sales, dtype: float64

In [ ]:
## R version
store %>% groupby(segment) %>% summarize(sum(sales))

In [ ]:
result = store.groupby(["segment", "category"])["sales"].sum().reset_index()

segment         category        sales
0     Consumer        Furniture  391049.3120
1     Consumer  Office Supplies  363952.1360
2     Consumer       Technology  406399.8970
3    Corporate        Furniture  229019.7858
4    Corporate  Office Supplies  230676.4620
5    Corporate       Technology  246450.1190
6  Home Office        Furniture  121930.6975
7  Home Office  Office Supplies  124418.4340
8  Home Office       Technology  183304.0170

In [ ]:
result.to_csv("agg_data.csv")

In [ ]:
# aggregate # \ ขึ้นบรรทัดใหม่
store.groupby("segment")["sales"].\
    agg(["sum", "mean", "std"]).\
    reset_index()

segment           sum        mean         std
0     Consumer  1.161401e+06  223.733644  585.516175
1    Corporate  7.061464e+05  233.823300  599.410408
2  Home Office  4.296531e+05  240.972041  755.516379

In [ ]:
## read data from sql database
## chinook.db

import sqlite3
import pandas as pd

## create connection
con = sqlite3.connect("chinook.db")

df = pd.read_sql("SELECT * FROM customers WHERE country = 'USA'", con)

# close connection
con.close()

In [ ]:
df.head()

CustomerId FirstName LastName                Company  \
0          16     Frank   Harris            Google Inc.   
1          17      Jack    Smith  Microsoft Corporation   
2          18  Michelle   Brooks                   None   
3          19       Tim    Goyer             Apple Inc.   
4          20       Dan   Miller                   None   

                     Address           City State Country  PostalCode  \
0  1600 Amphitheatre Parkway  Mountain View    CA     USA  94043-1351   
1            1 Microsoft Way        Redmond    WA     USA  98052-8300   
2               627 Broadway       New York    NY     USA  10012-2612   
3            1 Infinite Loop      Cupertino    CA     USA       95014   
4       541 Del Medio Avenue  Mountain View    CA     USA   94040-111   

               Phone                Fax                    Email  SupportRepId  
0  +1 (650) 253-0000  +1 (650) 253-0000       fharris@google.com             4  
1  +1 (425) 882-8080  +1 (425) 882-8081  jacksmith@microsoft.com             5  
2  +1 (212) 221-3546  +1 (212) 221-4679        michelleb@aol.com             3  
3  +1 (408) 996-1010  +1 (408) 996-1011         tgoyer@apple.com             3  
4  +1 (650) 644-3358               None      dmiller@comcast.com             4

In [ ]:
df[df.State == "WA"]

CustomerId FirstName LastName                Company          Address  \
1          17      Jack    Smith  Microsoft Corporation  1 Microsoft Way   

      City State Country  PostalCode              Phone                Fax  \
1  Redmond    WA     USA  98052-8300  +1 (425) 882-8080  +1 (425) 882-8081   

                     Email  SupportRepId  
1  jacksmith@microsoft.com             5